---
title: "Folien als PDFs"
output: html_document
---

Hier finden Sie Folien als PDFs zum Download:

# Lehrvideos

- [Einführung zu RMarkdown](slides/rmarkdown.pdf)
- [Datentypen in R](slides/data-types.pdf)
- [Wieso Git und Github](slides/Vorteile_Git-und-Github.pdf)
- [Programming Basics](slides/programming-basics.pdf)
- [Vektorarithmetik](slides/vector-arithmetics.pdf)
- [Daten in R importieren](slides/import-data.pdf)
- [Daten in die richtige Form bringen](slides/reshape-data.pdf)
- [Einführung in die Datenaufbereitung](slides/data-wrangling-intro.pdf)
- [Datensätze zusammenführen](slides/combine-tables.pdf)
- [Datum und Uhrzeit](slides/dates-and-time.pdf)
- [Einführung in ggplot](slides/visualisierung_mit_ggplot2.pdf)
- [Guidelines für die Visualisierung](slides/visualisierung-guidelines.pdf)
- [Korrelation](slides/correlation.pdf)
- [Advanced R Markdown](slides/advanced_rmarkdown.pdf)
- [Stichprobe vs. Grundgesamtheit](slides/sample-vs-population.pdf)
- [Koeffizienten Interpretieren](slides/koeffizienten_interpretieren.pdf)
- [Erste Eindrücke zu Kausalität](slides/causality1.pdf)
- [Directed acyclic graphs](slides/dag_video.pdf)

# Vorlesungen

- [Einführungsveranstaltung](slides/intro_projektkurs_data-science.pdf)
- [Case-Study Teil 1](slides/VL_case-study-Teil1.pdf)
- [Case-Study Teil 2](slides/VL_case-study-Teil2.pdf)
- [Einführungsveranstaltung zum 2. Teil](slides/intro_projektkurs_data-science2.pdf)
- [Wahrscheinlichkeiten und Konfidenzintervalle](slides/probability-and-confidence-interval.pdf)
- [Inferenzstatistik](slides/inference.pdf)
- [Lineare Regression](slides/linear-regression.pdf)
- [Case-Study Teil 3](slides/vl_case-study-teil3.pdf)
- [Kausalität in den Wirtschaftswissenschaften](slides/dag_slides.pdf)
- [Randomisiertes Experiment](slides/experiment_slides.pdf)
- [Instrumentalvariablen](slides/instruments.pdf)